### ISSUE TITLE
aws-alb-ingress可以考虑用Helm安装

### ISSUE THREAD

**Issue by pahud** [walkley/eks-workshop#3]
这边有用Helm安装的范例
https://github.com/pahud/aws-containers-workshop/tree/master/lab2#install-aws-alb-ingress-controller-with-helm

目前README里面是直接用kubectl apply -f 安装，这样容易存在版本过旧需要不断更新维护的问题

例如：

![image](https://user-images.githubusercontent.com/278432/59737419-29752600-9290-11e9-8d44-c4f066ad7f7b.png)

目前最新版本已经是`1.1.2`了
https://github.com/kubernetes-sigs/aws-alb-ingress-controller

**Comment by walkley** [comment]
已更新README，采用Helm安装ALB ingress controller
