### ISSUE TITLE
kubectl version 1.13.7 AWS S3 download URL

### ISSUE THREAD

**Issue by pahud** [walkley/eks-workshop#5]
这里已经提供了URL

https://github.com/awsdocs/amazon-eks-user-guide/blob/master/doc_source/install-kubectl.md

可以考虑直接下载`1.13.7`版本

![image](https://user-images.githubusercontent.com/278432/59810469-ecfd0500-9337-11e9-8421-86f97bceb3ce.png)

**Comment by walkley** [comment]
已更新到1.13.7
